# Cleaning of consolidated consumption dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [2]:
df_consumption = pd.read_csv("../../dataset/clean/production/tabular/consumption_consolidated.csv")
df_consumption.head()

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
0,0,Kho Shipping Lines,NaN,Bailon Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,121,"Almodal, Maricel",District 2,Esparrago Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
2,50964,"Esparraguerra, Irish",District 2,Fabmar Street,Residential,Unknown,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,500001,"Encinares, Roberto",District 4,Esparrago Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
4,500002,"Pareja, Myrna",District 4,Esparrago Street,Residential,Active,153.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,13.0,5.0,18.0,10.0,0.0,35.0,0.0,33.0,33.0,19.0,16.0,13.0,21.0,10.0,0.0,15.0,7.0,22.0,68.0,53.0,NaN,NaN,30.0,30.0,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,NaN,0.0,20.0,NaN,0.0,0.0,0.0,0.0,153.0

In [3]:
df_consumption.isnull().sum()

Control Number        0
Account Name       2154
District           2445
Street             2154
Connection Type    2161
                   ...
2025_JAN           2173
2025_FEB           2170
2025_MAR           2168
2025_APR           2166
2025_MAY           2162
Length: 61, dtype: int64

### Dropping Control Number duplicates

In [4]:
# Keep the first instance of the duplicate in df_consumption
df_consumption = df_consumption[~df_consumption.duplicated(subset=["Control Number"], keep="first")]
df_consumption.isnull().sum()

Control Number       0
Account Name         9
District           300
Street               9
Connection Type     16
                  ...
2025_JAN            28
2025_FEB            25
2025_MAR            23
2025_APR            21
2025_MAY            17
Length: 61, dtype: int64

In [6]:
# Display records with missing district
df_consumption[df_consumption["District"].isnull()]

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
0,0,Kho Shipping Lines,NaN,Bailon Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,500016,"Gutierrez, Robert",NaN,Moyot Street,Residential,Active,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,4.0,0.0,0.0,0.0,NaN,20.0,27.0,15.0,22.0,0.0,26.0,0.0,34.0,33.0,17.0,14.0,7.0,16.0,31.0,0.0,21.0,23.0,28.0,26.0,39.0,NaN,NaN,58.0,58.0,NaN,NaN,NaN,NaN,25.0,NaN,21.0,18.0,NaN,17.0,13.0,NaN,12.0,11.0,18.0,19.0,0.0
19,500017,"Almosara, Elsie",NaN,Moyot Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
20,500018,"Quijano, Asteria",NaN,Moyot Street,Residential,Active,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,18.0,10.0,20.0,20.0,NaN,22.0,13.0,24.0,11.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,240.0,34.0,34.0,0.0,43.0,44.0,54.0,36.0,93.0,NaN,NaN,50.0,50.0,NaN,NaN,NaN,NaN,45.0,NaN,45.0,52.0,NaN,43.0,47.0,NaN,137.0,98.0,15.0,12.0,0.0
39,500037,"Espera, Nory",NaN,Moyot Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4191,502014,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4325,502556,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4326,504004,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4327,504008,NaN,NaN,NaN,NaN,Unknown,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4328,507076,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Filling in missing account names

#### V1 - 8/27/25

In [11]:
df_account_names = pd.read_csv("../../dataset/clean/production/tabular/consolidated_readings_with_account_names.csv")

# Create a mapping from Control Number to Account Name in df_account_names, keeping the first occurrence
control_to_name = df_account_names.drop_duplicates(subset="Control Number").set_index("Control Number")["Account Name"]

# Update Account Name in df where Control Number matches
df_consumption["Account Name"] = df_consumption["Control Number"].map(control_to_name).combine_first(df_consumption["Account Name"])

# Display head
df_consumption.head()

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
0,0,Kho Shipping Lines,NaN,Bailon Street,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,121,"Almodal, Maricel",District 2,Esparrago Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
2,50964,"Esparraguerra, Irish",District 2,Fabmar Street,Residential,Unknown,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,500001,"Encinares, Roberto",District 4,Esparrago Street,Residential,Disconnected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
4,500002,"Pareja, Myrna",District 4,Esparrago Street,Residential,Active,153.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,13.0,5.0,18.0,10.0,0.0,35.0,0.0,33.0,33.0,19.0,16.0,13.0,21.0,10.0,0.0,15.0,7.0,22.0,68.0,53.0,NaN,NaN,30.0,30.0,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,NaN,0.0,20.0,NaN,0.0,0.0,0.0,0.0,153.0

In [14]:
df_consumption[df_consumption["Account Name"].isnull()]

,Control Number,Account Name,District,Street,Connection Type,Connection Status,Last Reading,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
2175,000000,NaN,NaN,NaN,NaN,Unknown,107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2176,000121,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2177,000nan,NaN,NaN,NaN,NaN,Unknown,0.0,2.444444,7.571429,2.333333,0.0,0.0,0.0,4.0,NaN,NaN,NaN,NaN,NaN,2.444444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,0.0,NaN,NaN,0.0,19.0,85.0,230.5,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2178,050964,NaN,NaN,NaN,NaN,Unknown,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4191,502014,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4325,502556,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4326,504004,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4327,504008,NaN,NaN,NaN,NaN,Unknown,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4328,507076,NaN,NaN,NaN,NaN,Unknown,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Status: Failed
No records for the missing account name

In [15]:
# Export missing Account Names
missing_accounts = df_consumption[df_consumption["Account Name"].isnull()]
missing_accounts.to_csv("../../dataset/clean/production/misc/missing_account_names.csv", index=False)

#### V2